version: '3'

services:
  database:
    image: postgres:12
    container_name: postgres
    volumes:
      - mdb-data:/var/lib/postgresql/data
      - ./sql/create.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '127.0.0.1:5432:5432'
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=testuser
      - POSTGRES_DB=machinable

  redis:
    image: redis
    container_name: cache
    expose:
      - 6379

  events:
    image: 'docker.pkg.github.com/machinable/event-processor/event-processor:0.5.3'
    container_name: events
    restart: always
    depends_on:
      - 'redis'
    environment:
      - REDIS_ADDR=
      - REDIS_PW=

  notifications:
    image: 'docker.pkg.github.com/anothrnick/email-notifications/email-notifications:1.0.2'
    container_name: notifications
    restart: always
    depends_on:
      - 'redis'
    volumes:
    - ./usr/config.json:/usr/config.json
    - ./templates/:/templates/
    environment:
      - EMAIL_CONFIG_PATH=/usr/config.json
      - SENDGRID_API_KEY

  api:
    container_name: machinable
    image: 'docker.pkg.github.com/machinable/machinable/machinable:1.2.0'
    restart: always
    depends_on:
      - 'database'
      - 'redis'
    ports:
      - '127.0.0.1:5002:5001'
    volumes:
      - ./usr/config.json:/usr/config.json
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PW=1234
      - POSTGRES_HOST=database
      - POSTGRES_DB=machinable
      - SCHEME=https
      - MACHINABLE_CONFIG_PATH=/usr/config.json

  # ui:
  #   container_name: ui
  #   image: 'docker.pkg.github.com/machinable/machinable-ui/ui:1.1.1'
  #   restart: always
  #   ports:
  #     - '127.0.0.1:5003:80'

volumes:
  mdb-data: