version: '2'
services:

  stats:
    image: docker.pkg.github.com/anothrnick/send-query-result/app:0.6.0
    container_name: query_stats
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PW=1234
      - POSTGRES_HOST=database
      - POSTGRES_DB=testdb
      - POSTGRES_SSL=disable
      - STAT_QUERY
      - STAT_INTERVAL
      - STAT_URL

  database:
    image: postgres:12
    container_name: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./sql/create.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '127.0.0.1:5432:5432'
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=testuser
      - POSTGRES_DB=testdb

  redis:
    image: redis
    container_name: cache
    ports:
      - '127.0.0.1:6379:6379'

  events:
    image: 'docker.pkg.github.com/machinable/event-processor/event-processor:0.5.3'
    container_name: events
    restart: always
    depends_on:
      - 'redis'
    environment:
      - REDIS_ADDR=
      - REDIS_PW=

  notifications:
    image: 'docker.pkg.github.com/anothrnick/email-notifications/email-notifications:1.0.2'
    container_name: notifications
    restart: always
    depends_on:
      - 'redis'
    volumes:
    - ./config/sample-config.json:/usr/config.json
    - ./local/templates/:/templates/
    environment:
      - EMAIL_CONFIG_PATH=/usr/config.json
      - SENDGRID_API_KEY

  api:
    build: 
      context: .
      dockerfile: Dockerfile
      args:                                                                      
        VERSION: $VERSION
    container_name: machinable_api
    depends_on:
      - 'database'
      - 'redis'
    ports:
    - "127.0.0.1:5001:5001"
    volumes:
    - ./config/sample-config.json:/usr/config.json
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PW=1234
      - POSTGRES_HOST=database
      - POSTGRES_DB=testdb
      - MACHINABLE_CONFIG_PATH=/usr/config.json
      - APP_SECRET
      - RECAPTCHA_SECRET
      - IPSTACK_KEY

volumes:
  db-data:
