version: '2'
services:

  database:
    image: postgres:12
    container_name: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./sql/create.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '127.0.0.1:5432:5432'
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=testuser
      - POSTGRES_DB=testdb

  events:
    image: 'docker.pkg.github.com/machinable/event-processor/event-processor:0.5.3'
    container_name: events
    restart: always
    depends_on:
      - 'redis'
    environment:
      - REDIS_ADDR=
      - REDIS_PW=

  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: machinable_api
    depends_on:
      - 'database'
      - 'redis'
    ports:
    - "127.0.0.1:5001:5001"
    volumes:
    - ./config/sample-config.json:/usr/config.json
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PW=1234
      - POSTGRES_HOST=database
      - POSTGRES_DB=testdb
      - MACHINABLE_CONFIG_PATH=/usr/config.json
      - APP_SECRET
      - RECAPTCHA_SECRET
      - IPSTACK_KEY


volumes:
  db-data:
